# Algebra Linear

A álgebra linear é um ramo fundamental da matemática que lida com vetores, espaços vetoriais (também chamados de espaços lineares), transformações lineares e sistemas de equações lineares. Ela fornece as ferramentas matemáticas para descrever e manipular conjuntos de dados em muitas áreas da ciência, especialmente na ciência de dados, inteligência artificial (IA), machine learning (ML) e deep learning (DL).

Aqui estão alguns conceitos e fundamentos-chave da álgebra linear:

1. Escalares:
Definição: Um escalar é um número real (ou complexo) que multiplica vetores ou matrizes. Escalares são frequentemente usados para ajustar a magnitude de vetores ou para realizar operações aritméticas simples em sistemas lineares.

2. Vetores:
Definição: Um vetor é uma entidade matemática que tem magnitude e direção. Em álgebra linear, os vetores são frequentemente representados como uma lista ordenada de números (um array unidimensional) que pode ser visualizada como um ponto no espaço n-dimensional.

3. Matrizes:
Definição: Uma matriz é uma tabela retangular de números organizada em linhas e colunas. Matematicamente, uma matriz pode ser vista como uma transformação linear que atua sobre vetores para mapear um espaço vetorial em outro.
Tipos de Matrizes:
Matriz Quadrada: Número de linhas igual ao número de colunas.
Matriz Diagonal: Uma matriz quadrada onde todos os elementos fora da diagonal principal são zeros.
Matriz Identidade: Uma matriz diagonal onde todos os elementos da diagonal principal são iguais a 1.
Matriz Transposta: Obtida ao trocar linhas por colunas em uma matriz.

4. Espaços Vetoriais:
Definição: Um espaço vetorial é um conjunto de vetores que pode ser escalado e adicionado entre si, obedecendo a certas regras (axiomas).

5. Transformações Lineares:
Definição: São funções que mapeiam vetores de um espaço vetorial para outro, preservando operações de adição vetorial e multiplicação por escalares.
Exemplo: Uma rotação de um vetor no plano 2D é uma transformação linear.
6. Autovalores e Autovetores:

Eles são usados para entender propriedades fundamentais de transformações lineares, como rotações e escalamentos.
Exemplo: Em redes neurais, autovalores e autovetores podem ser usados para estudar a convergência de algoritmos de otimização.
Usos em IA, ML e DL:
IA (Inteligência Artificial):

Processamento de Imagens: Matrizes são usadas para representar pixels em imagens e vetores são usados para representar características extraídas das imagens.
Redes Neurais: Operações matriciais são fundamentais para a propagação de sinais e para o treinamento de redes neurais.
ML (Machine Learning):

Algoritmos de Regressão e Classificação: Usam operações matriciais para calcular funções de custo e para ajustar modelos (ex.: regressão linear, regressão logística).
Redução de Dimensionalidade: Técnicas como PCA (Análise de Componentes Principais) usam álgebra linear para reduzir a dimensionalidade dos dados.
DL (Deep Learning):

Camadas de Redes Neurais: Cada camada em uma rede neural profunda é uma transformação linear seguida por uma não-linearidade. A álgebra linear é usada para computar essas transformações.
Backpropagation: O algoritmo de backpropagation, usado para treinar redes neurais, depende fortemente de operações matriciais.
Outros Usos:
Física e Engenharia: Representação de sistemas físicos, como equações diferenciais e sistemas dinâmicos, frequentemente usa álgebra linear.
Computação Gráfica: Operações como rotação, translação e escalonamento de objetos 3D são realizadas usando transformações lineares.
Economia e Finanças: Modelagem de sistemas econômicos e análise de portfólios utilizam vetores e matrizes para representar e resolver problemas.
A álgebra linear é, portanto, uma das bases matemáticas mais importantes para quem trabalha com ciência de dados e inteligência artificial, fornecendo as ferramentas para manipular e entender grandes conjuntos de dados e modelos complexos.

In [1]:
import numpy as np

1. Matriz Diagonal
Conceito:

Uma matriz diagonal é uma matriz quadrada em que todos os elementos fora da diagonal principal são zero.
Fundamentos.

Se
𝐴
A é uma matriz diagonal, então
𝐴
[
𝑖
,
𝑗
]
=
0
A[i,j]=0 para todo
𝑖
≠
𝑗
i

=j.
A diagonal principal pode conter valores diferentes de zero.
Aplicações:

Simplificação de operações matriciais, como multiplicação.
Em álgebra linear, as matrizes diagonais são usadas na diagonalização de matrizes.
Em métodos numéricos, como a decomposição de valores singulares (SVD).

In [9]:
#Exemplo de Matriz Diagonal
np.diag([1,5,7,9,10,11,12,13,14,15,16,17,18,19,20,21])

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 13,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 14,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 15,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 16,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 17,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

2. Matriz Coluna
Conceito:

Uma matriz coluna é uma matriz que consiste em um único vetor de dimensão
𝑛
×
1
n×1, ou seja, uma matriz com apenas uma coluna e várias linhas.
Fundamentos:

Se
𝐴
A é uma matriz coluna, ela tem a forma
𝐴
=
[
𝑎
1
𝑎
2
⋮
𝑎
𝑛
]
A=
​
  
a
1
​

a
2
​

⋮
a
n
​

​
  
​
 , onde cada
𝑎
𝑖
a
i
​
  é um elemento da matriz.
Uma matriz coluna é comumente usada para representar vetores em álgebra linear.
Aplicações:

Usada para representar vetores em espaços vetoriais.
Importante em sistemas lineares, onde os vetores solução e os vetores de termos constantes são representados como matrizes coluna.
Em métodos de otimização, as variáveis e restrições são frequentemente representadas como matrizes coluna.

In [3]:
#Matriz Coluna
MColuna = np.array([[2],[-4],[6],[-10],[11]])
MColuna

array([[  2],
       [ -4],
       [  6],
       [-10],
       [ 11]])

In [10]:
#Exemplo de Matriz coluna usando Transpose
MColuna1 = np.transpose([[2,-4,6,-10,11]])
MColuna1

array([[  2],
       [ -4],
       [  6],
       [-10],
       [ 11]])

3. Matriz Nula (ou Matriz Zero)
Conceito:

Uma matriz nula é uma matriz em que todos os elementos são iguais a zero.
Fundamentos:

Representada geralmente por
0
0, independentemente da sua dimensão.
Na multiplicação de matrizes, qualquer matriz multiplicada por uma matriz nula resulta em uma matriz nula.
Aplicações:

Usada em análises onde o efeito nulo de uma operação é importante.
Base para representar sistemas lineares homogêneos

In [11]:
#Exemplo de Matriz Zeros
Mzeros = np.zeros((11,11))
Mzeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

4. Matriz Identidade
Conceito:

Uma matriz identidade é uma matriz diagonal onde todos os elementos da diagonal principal são iguais a 1.
Fundamentos:

Denotada por
𝐼
I, a matriz identidade de ordem
𝑛
n é a matriz
𝑛
×
𝑛
n×n onde
𝐼
[
𝑖
,
𝑗
]
=
1
I[i,j]=1 se
𝑖
=
𝑗
i=j, e
𝐼
[
𝑖
,
𝑗
]
=
0
I[i,j]=0 se
𝑖
≠
𝑗
i

=j.
A matriz identidade é o elemento neutro na multiplicação de matrizes.
Aplicações:

Em álgebra linear, para manter inalterado o vetor ou matriz ao ser multiplicado.
Em algoritmos de otimização e resolução de sistemas lineares.

In [13]:
#Exemplo de Matriz Identidade
Midentidade = np.identity(11)
Midentidade

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

5. Transposta de uma Matriz
Conceito:

A transposta de uma matriz
𝐴
A é uma nova matriz
𝐴
𝑇
A
T
  obtida trocando as linhas e colunas de
𝐴
A.
Fundamentos:

Se
𝐴
A é uma matriz de dimensão
𝑚
×
𝑛
m×n, a sua transposta
𝐴
𝑇
A
T
  será uma matriz de dimensão
𝑛
×
𝑚
n×m.
Formalmente,
𝐴
𝑇
[
𝑖
,
𝑗
]
=
𝐴
[
𝑗
,
𝑖
]
A
T
 [i,j]=A[j,i].
A transposição é uma operação fundamental em álgebra linear, usada em diversas manipulações e transformações de matrizes.
Aplicações:

Em operações com matrizes, a transposição é usada para resolver sistemas lineares, calcular produtos internos e externos de vetores, e em decomposições matriciais.
Usada para simplificar expressões em matemática aplicada, como no cálculo de derivadas matriciais em otimização.
Em processamento de sinais, a transposição pode ser usada para modificar a orientação de sinais representados como matrizes.

In [7]:
#Matriz Transposta
MTransposta = np.array([[1,0,3],[2,1,4]])
print('MTransposta=',MTransposta)

MTransposta= [[1 0 3]
 [2 1 4]]


In [8]:
At = np.transpose(MTransposta)
print('At=',At)

At= [[1 2]
 [0 1]
 [3 4]]


In [14]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz original:\n", A)
print("Matriz transposta:\n", A.T)

Matriz original:
 [[1 2 3]
 [4 5 6]]
Matriz transposta:
 [[1 4]
 [2 5]
 [3 6]]


In [15]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print("Matriz original:\n", B)
print("Matriz transposta:\n", B.T)

Matriz original:
 [[1 2]
 [3 4]
 [5 6]]
Matriz transposta:
 [[1 3 5]
 [2 4 6]]


6. Matriz Hermitiana
Conceito:

Uma matriz hermitiana é uma matriz quadrada complexa que é igual à sua transposta conjugada.
Fundamentos:

Se
𝐴
A é uma matriz hermitiana, então
𝐴
[
𝑖
,
𝑗
]
=
𝐴
[
𝑗
,
𝑖
]
‾
A[i,j]=
A[j,i]
​
 , onde
𝐴
[
𝑗
,
𝑖
]
‾
A[j,i]
​
  é o conjugado complexo de
𝐴
[
𝑗
,
𝑖
]
A[j,i].
Se a matriz for real, uma matriz hermitiana é equivalente a uma matriz simétrica.
Aplicações:

Usada em física quântica e outras áreas onde as propriedades de auto-adjuntividade são importantes.
Em álgebra linear, as matrizes hermitianas têm autovalores reais.

In [16]:
import numpy as np
A = np.array([[1, 2+1j], [2-1j, 3]])
print(A)
print(np.allclose(A, A.T.conj()))  # Verifica se a matriz é hermitiana

[[1.+0.j 2.+1.j]
 [2.-1.j 3.+0.j]]
True


7. Matriz de Permutação
Conceito:

Uma matriz de permutação é uma matriz quadrada obtida permutando as linhas de uma matriz identidade.
Fundamentos:

Na matriz de permutação, cada linha e coluna contém exatamente um elemento igual a 1, com todos os outros elementos iguais a 0.
Usada para permutar as linhas ou colunas de outra matriz.
Aplicações:

Em álgebra linear e computação, é usada para rearranjar as linhas ou colunas de uma matriz.
Importante em algoritmos de ordenação e operações com matrizes esparsas.

In [17]:
import numpy as np
P = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
print(P)

[[0 1 0]
 [1 0 0]
 [0 0 1]]


8. Matriz Ortogonal
Conceito:

Uma matriz ortogonal é uma matriz quadrada cuja inversa é igual à sua transposta, ou seja,
𝐴
𝑇
=
𝐴
−
1
A
T
 =A
−1
 .
Fundamentos:

Uma matriz
𝐴
A é ortogonal se suas colunas e linhas forem vetores ortonormais.
O produto de duas matrizes ortogonais é também uma matriz ortogonal.
Aplicações:

Transformações ortogonais preservam a norma dos vetores e são amplamente utilizadas em computação gráfica e processamento de sinais.
Em álgebra linear, as matrizes ortogonais são usadas na decomposição QR.

In [18]:
import numpy as np
from scipy.linalg import orth
A = np.array([[1, 0], [0, -1]])
print(A)
print(np.allclose(A.T @ A, np.eye(2)))  # Verifica se a matriz é ortogonal

[[ 1  0]
 [ 0 -1]]
True


9. Matriz Triangular (Superior e Inferior)
Conceito:

Uma matriz triangular superior tem todos os elementos abaixo da diagonal principal iguais a zero.
Uma matriz triangular inferior tem todos os elementos acima da diagonal principal iguais a zero.
Fundamentos:

Triangular Superior:
𝐴
[
𝑖
,
𝑗
]
=
0
A[i,j]=0 para todo
𝑖
>
𝑗
i>j.
Triangular Inferior:
𝐴
[
𝑖
,
𝑗
]
=
0
A[i,j]=0 para todo
𝑖
<
𝑗
i<j.
Aplicações:

Simplificação de sistemas lineares (por exemplo, no método de eliminação de Gauss).
Importante em algoritmos de decomposição, como a decomposição LU

In [19]:
import numpy as np
A = np.array([[1, 2, 3], [0, 4, 5], [0, 0, 6]])  # Triangular Superior
B = np.array([[1, 0, 0], [2, 4, 0], [3, 5, 6]])  # Triangular Inferior
print("Triangular Superior:\n", A)
print("Triangular Inferior:\n", B)

Triangular Superior:
 [[1 2 3]
 [0 4 5]
 [0 0 6]]
Triangular Inferior:
 [[1 0 0]
 [2 4 0]
 [3 5 6]]


10. Matriz Simétrica
Conceito:

Uma matriz simétrica é uma matriz quadrada que é igual à sua transposta, ou seja,
𝐴
=
𝐴
𝑇
A=A
T
 .
Fundamentos:

Para uma matriz
𝐴
A ser simétrica, deve-se ter
𝐴
[
𝑖
,
𝑗
]
=
𝐴
[
𝑗
,
𝑖
]
A[i,j]=A[j,i] para todos os
𝑖
i e
𝑗
j.
Os valores na diagonal principal podem ser qualquer número.
Aplicações:

Usada em álgebra linear, especialmente em decomposições espectrais.
Importante em física, economia e outras disciplinas onde simetria é uma característica fundamental do sistema.

In [20]:
import numpy as np
A = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
print(A)
print(np.allclose(A, A.T))  # Verifica se a matriz é simétrica

[[1 2 3]
 [2 4 5]
 [3 5 6]]
True


11. Matriz Linha
Conceito:

Uma matriz linha é uma matriz que consiste em um único vetor de dimensão
1
×
𝑛
1×n, ou seja, uma matriz com apenas uma linha e várias colunas.
Fundamentos:

Se
𝐴
A é uma matriz linha, ela tem a forma
𝐴
=
[
𝑎
1
𝑎
2
…
𝑎
𝑛
]
A=[
a
1  
a
2  
a
n
 ], onde cada 𝑎
𝑖
a
i  é um elemento da matriz.
Uma matriz linha é frequentemente usada para representar vetores em álgebra linear.
Aplicações:

Representação de vetores como listas de elementos.
Utilizada em operações matriciais, como produtos matriciais, onde a multiplicação de uma matriz linha por uma matriz coluna resulta em um escalar.
Comum em diversas aplicações de processamento de dados e análise vetorial.

In [21]:
import numpy as np
R = np.array([[1, 2, 3]])
print(R)

[[1 2 3]]


12. Matriz Esparsa
Conceito:

Uma matriz esparsa é uma matriz onde a maioria dos elementos são zeros. Somente alguns elementos têm valores diferentes de zero.
Fundamentos:

Em uma matriz esparsa, a eficiência do armazenamento é maximizada ao usar estruturas de dados especiais que armazenam apenas os elementos não nulos.
As operações com matrizes esparsas são otimizadas para evitar a multiplicação e adição de zeros.
Aplicações:

Em ciência da computação, especialmente em algoritmos que lidam com grandes conjuntos de dados onde a maioria dos valores são zeros, como em gráficos e processamento de imagem.
Usada em métodos numéricos para resolver sistemas de equações lineares com coeficientes esparsos.
Em machine learning, especialmente em métodos que utilizam representações de dados esparsos, como em sistemas de recomendação.

In [22]:
from scipy.sparse import csr_matrix
S = csr_matrix([[0, 0, 1], [1, 0, 0], [0, 0, 0]])
print(S)

  (0, 2)	1
  (1, 0)	1


13. Matriz Ortogonalizada (ou Ortonormal)
Conceito:

Uma matriz ortogonalizada ou ortonormal é uma matriz cujas colunas (ou linhas) são vetores ortonormais, ou seja, são mutuamente ortogonais e têm norma 1.
Fundamentos:

Se
𝑄
Q é uma matriz ortonormal, então
𝑄
𝑇
𝑄
=
𝐼
Q
T
 Q=I, onde
𝐼
I é a matriz identidade.
A ortogonalização de uma matriz é realizada pelo processo de Gram-Schmidt.
Aplicações:

Em álgebra linear, usada para a decomposição QR e em várias aplicações que requerem a preservação de comprimentos e ângulos, como em transformações geométricas.
Utilizada em processamento de sinais e compressão de dados, como na Transformada Discreta de Cosseno (DCT).

In [23]:
import numpy as np
from scipy.linalg import qr
A = np.array([[1, 1], [1, -1]])
Q, R = qr(A)
print("Matriz ortonormal Q:\n", Q)

Matriz ortonormal Q:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


14. Matriz de Hankel
Conceito:

Uma matriz de Hankel é uma matriz onde cada elemento na diagonal que vai da esquerda inferior para a direita superior é constante.
Fundamentos:

Se
𝐴
A é uma matriz de Hankel, então
𝐴
[
𝑖
,
𝑗
]
=
𝐴
[
𝑖
+
1
,
𝑗
−
1
]
A[i,j]=A[i+1,j−1].
Geralmente, é usada na teoria de sistemas e processamento de sinais.
Aplicações:

Em análise de séries temporais, a matriz de Hankel é usada para converter uma série temporal em uma matriz de amostras.
Em álgebra linear, utilizada em técnicas de aproximação de matrizes e decomposição espectral.

In [24]:
import numpy as np
from scipy.linalg import hankel
c = np.array([1, 2, 3])
r = np.array([3, 4, 5, 6])
H = hankel(c, r)
print(H)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


15. Matriz de Toeplitz
Conceito:

Uma matriz de Toeplitz é uma matriz onde cada diagonal que vai da esquerda superior para a direita inferior é constante.
Fundamentos:

Se
𝐴
A é uma matriz de Toeplitz, então
𝐴
[
𝑖
,
𝑗
]
=
𝐴
[
𝑖
−
1
,
𝑗
−
1
]
A[i,j]=A[i−1,j−1].
Essa estrutura é útil para representar sistemas lineares invariantes no tempo.
Aplicações:

Em processamento de sinais, a matriz de Toeplitz é usada em filtros digitais e problemas de convolução.
Utilizada em soluções numéricas de equações diferenciais e sistemas lineares com estrutura de convolução.

In [25]:
import numpy as np
from scipy.linalg import toeplitz
c = np.array([1, 2, 3])
r = np.array([1, 4, 5, 6])
T = toeplitz(c, r)
print(T)

[[1 4 5 6]
 [2 1 4 5]
 [3 2 1 4]]


16. Matriz Bloco
Conceito:

Uma matriz bloco é uma matriz composta por blocos menores, que podem ser matrizes de tamanhos variados.
Fundamentos:

As matrizes blocos permitem a simplificação de operações matriciais complexas dividindo uma grande matriz em partes menores e mais manejáveis.
As operações são realizadas nos blocos individualmente.
Aplicações:

Em álgebra linear, a decomposição em blocos é usada para resolver sistemas de equações lineares complexas.
Em sistemas de controle e processamento de sinais, onde as matrizes blocos representam diferentes subsistemas.

In [26]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])
D = np.array([[13, 14], [15, 16]])
Block_Matrix = np.block([[A, B], [C, D]])
print(Block_Matrix)

[[ 1  2  5  6]
 [ 3  4  7  8]
 [ 9 10 13 14]
 [11 12 15 16]]


17. Matriz de Vandermonde
Conceito:

Uma matriz de Vandermonde é uma matriz em que cada linha é uma progressão geométrica, geralmente usada em interpolações polinomiais.
Fundamentos:

Se
𝑥
1
,
𝑥
2
,
…
,
𝑥
𝑛
x
1
​
 ,x
2
​
 ,…,x
n
​
  são números distintos, a matriz de Vandermonde é dada por
𝑉
[
𝑖
,
𝑗
]
=
𝑥
𝑖
𝑗
−
1
V[i,j]=x
i
j−1
​
 .
Aplicações:

Em álgebra linear e análise numérica, para resolver sistemas de equações lineares envolvendo polinômios.
Utilizada em interpolação polinomial e problemas de ajuste de curvas.

In [27]:
import numpy as np
x = np.array([1, 2, 3])
V = np.vander(x, increasing=True)
print(V)

[[1 1 1]
 [1 2 4]
 [1 3 9]]


18. Matriz de Rotação
Conceito:

Uma matriz de rotação é uma matriz ortogonal usada para rotacionar vetores em espaços 2D ou 3D.
Fundamentos:

Em 2D, a matriz de rotação para um ângulo
𝜃
θ é dada por:
𝑅
(
𝜃
)
=
[
cos
⁡
(
𝜃
)
−
sin
⁡
(
𝜃
)
sin
⁡
(
𝜃
)
cos
⁡
(
𝜃
)
]
R(θ)=[
cos(θ)
sin(θ)
​
  
−sin(θ)
cos(θ)
​
 ]
Em 3D, a rotação pode ocorrer em torno de qualquer eixo (x, y ou z), com matrizes específicas para cada caso.
Aplicações:

Em computação gráfica, simulações físicas e robótica, onde a rotação de objetos no espaço é essencial.
Em álgebra linear, as matrizes de rotação são usadas em transformações geométricas e análise de sinais.

In [28]:
import numpy as np
theta = np.radians(45)
R = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
print(R)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


# Validação de Matrizes

In [29]:
A = np.array([[1, 2], [3,4]])
B = np.array([[5, 6], [7, 8]])
A == B

array([[False, False],
       [False, False]])

In [30]:
(A + B).T == A.T + B.T

array([[ True,  True],
       [ True,  True]])

In [31]:
(A.T).T == A

array([[ True,  True],
       [ True,  True]])

In [32]:
(77 * A).T == 77 * A.T

array([[ True,  True],
       [ True,  True]])

In [33]:
(A * B).T == B.T * A.T

array([[ True,  True],
       [ True,  True]])

# Operações com vetores e escalares

In [35]:
a=2 #escalar
v1=np.array([1,2,3,4,5]) #vetor
r1=v1+2 #adciona o escalar 2 a cada elemento do vetor
print('r1=',r1)

r1= [3 4 5 6 7]


In [37]:
b=3
c=10
r2=(v1*b)/c
print('r2=',r2)

r2= [0.3 0.6 0.9 1.2 1.5]
